name: 'Pull request rules'
description: 'Github action to enforce pull request conventions'
inputs:
  title_regex:
    description: 'Regex to validate the pull request title'
    default: '.+'
    required: false
  title_regex_flags:
    description: 'Flags to use for the regex to validate the pull request title'
    default: ''
    required: false
  title_allowed_prefixes:
    description: 'Comma separated list of prefix allowed to be used in pull request title. eg: feature,hotfix,JIRA-'
    default: ''
    required: false
  title_prefix_case_sensitive:
    description: 'Are the allowed pull request title prefixes case sensitive?'
    default: 'false'
    required: false

  labels_required:
    description: 'Comma separated list of label names, of which the pull request must have at least one. eg: enhancement,bug'
    default: 'DEV,QED'
    required: true

  assignee_required:
    description: 'Whether the pull request should require an assignee.'
    default: 'false'
    required: false

  project_required:
    description: 'Whether the pull request should require a project.'
    default: 'false'
    required: false

  repo_token:
    description: 'Access token to be used to comment on pull requests with validation issues. Can be passed in as {{ secrets.GITHUB_TOKEN }}'
    default: ''
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
