on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate:
    name: Validate pull request fields
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: ./.github/actions/pull-request-validation
        with:
          title_regex: '^([0-9]+|N\/A|WIP) - .+$'
          labels_required: true
          assignee_required: true
          project_required: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}